# Generated by Django 6.0.3 on 2026-06-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('autor', models.CharField(max_length=150)),
                ('ano', models.PositiveIntegerField()),
                ('editora', models.CharField(max_length=150)),
                ('isbn', models.CharField(max_length=13)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
    ]
