# Generated by Django 6.0.3 on 2026-07-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('autor', models.CharField(max_length=150)),
                ('ano', models.PositiveIntegerField(blank=True, null=True)),
                ('editora', models.CharField(blank=True, max_length=150, null=True)),
                ('obra_id', models.CharField(max_length=50, unique=True)),
                ('quantidade', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
