# Generated by Django 6.0.3 on 2026-07-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LivroApp', '0002_alter_livro_editora_alter_livro_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
